In [120]:
#import all the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
import sklearn.datasets as datasets


In [121]:
#split iris dataset 
iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [122]:
#show data and column names
print("Column names: ", iris.feature_names)
print("total features: ", X_train.shape[1])
#target names
print("Target names: ", iris.target_names)

Column names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
total features:  4
Target names:  ['setosa' 'versicolor' 'virginica']


In [123]:
#show data
print("X_train: ", X_train[:6])
print("y_train: ", y_train[:6])
print("X_test: ", X_test.shape)

X_train:  [[6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]]
y_train:  [2 1 0 2 2 1]
X_test:  (30, 4)


In [124]:
import numpy as np
from collections import Counter
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))


def k_nearest_neighbors(X_train, y_train, X_test, k=3):
    
    for x,i in enumerate(X_test):
      distances = []
      labels = []
      for ind,j in enumerate(X_train):
        distance = euclidean_distance(i, j)
        distances.append((distance, ind))
      print(distances)
      distances = sorted(distances)[:k]
      for d, ii in distances:
        labels.append(y_train[ii])
      most_com={}
      #Counter(labels).most_common(1)[0][0]
      for x in labels:
        if most_com.get(x)==None:
            most_com[x]=1
        else:
            most_com[x]+=1
      maxi=0
      for x in most_com:
        if most_com[x]>maxi:
            maxi=x
            
      print(f"Label for {x} point: ",labels," ---> ",maxi)

 

In [129]:

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

def KNN(X_train, y_train, X_test, k=3):
    predictions = []
    for test_index, x_test in enumerate(X_test):
        distances = []
         
        for train_index, x_train in enumerate(X_train):
            d = euclidean_distance(x_test,x_train)
            distances.append((d,train_index))
        distances = sorted(distances)[:k]

        labels = [y_train[i] for d,i in distances]
        prediction = Counter(labels).most_common(1)[0][0]
        predictions.append(prediction)
        print(f"Test point {test_index} --> {prediction}")
    return predictions
 

In [130]:
predictions = KNN(X_train, y_train, X_test, k=3)

Test point 0 --> 2
Test point 1 --> 1
Test point 2 --> 0
Test point 3 --> 2
Test point 4 --> 0
Test point 5 --> 2
Test point 6 --> 0
Test point 7 --> 1
Test point 8 --> 1
Test point 9 --> 1
Test point 10 --> 2
Test point 11 --> 1
Test point 12 --> 1
Test point 13 --> 1
Test point 14 --> 2
Test point 15 --> 0
Test point 16 --> 1
Test point 17 --> 1
Test point 18 --> 0
Test point 19 --> 0
Test point 20 --> 2
Test point 21 --> 1
Test point 22 --> 0
Test point 23 --> 0
Test point 24 --> 2
Test point 25 --> 0
Test point 26 --> 0
Test point 27 --> 1
Test point 28 --> 1
Test point 29 --> 0


In [131]:
#show accuracy using sklearn
print("Accuracy score: ", accuracy_score(y_test, predictions))

Accuracy score:  0.9666666666666667


In [136]:

#show confusion matrix
print("Confusion matrix: \n", confusion_matrix(y_test, predictions))
#show f1 
print("F1 score: ", f1_score(y_test, predictions, average='macro'))


Confusion matrix: 
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
F1 score:  0.9610256410256409


In [137]:
#knn using sklearn
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Confusion matrix: \n", confusion_matrix(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred, average='macro'))

Accuracy score:  0.9666666666666667
Confusion matrix: 
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
F1 score:  0.9610256410256409


c:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
